Initiate API spec
square-it/flogo-demo-iot pull request #1
Opened 2018-10-25 15:05 UTC by debovema

A simple Swagger API spec to review and enhance

2018-10-25 15:13 UTC, ffassler requested changes
The Smiley definition is not used. Should be removed?

2018-10-26 14:09 UTC, emilienthomas requested changes
Would rather use a string for smileyId

2018-10-26 16:56 UTC, debovema reviewed
OK to change *smileyId* to a string. This will allow to request the display of a smiley directly with its string representation if I understand well, such as *:some_smiley:* or maybe *:)*.

2018-10-29 13:19 UTC, ffassler commented on swagger.yaml
> +        type: "integer"
```suggestion
        type: "string"
```

2018-10-29 13:19 UTC, ffassler commented on swagger.yaml
> +        format: "int64"
```suggestion
```

2018-10-29 13:21 UTC, ffassler commented on swagger.yaml
> +        description: "ID of smiley to display"
```suggestion
        description: "ID of smiley to display or string representation of smiley like :some_smiley:"
```

2018-10-29 13:22 UTC, ffassler requested changes
change smileyId to a string. This will allow to request the display of a smiley directly with its string representation such as :some_smiley:

2018-10-29 20:41 UTC, merged